semi: false
proseWrap: preserve
overrides:
  - files: "*.js"
    options:
      tabWidth: 2
printWidth: 120
singleAttributePerLine: false
trailingComma: none
noBracketSpacing: true
html-whitespace-sensitivity: ignore
experimentalTernaries: true

