name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_DEMO_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEMO_PROJECT_ID }}
#  SUPABASE_URL: ${{ secrets.SUPABASE_DEMO_URL }}
#  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_DEMO_SERVICE_KEY }}
#  SUPABASE_KEY: ${{ secrets.SUPABASE_DEMO_KEY }}

on:
  push:
    branches:
      - demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install Vercel CLI
        run: bun i -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm