name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
# checks if commit message contains 'vercel-deploy'
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      trigger: ${{ steps.check.outputs.trigger }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check commit
        id: check
        run: |
          echo "::set-output name=trigger::$(git log -1 --pretty=%B | grep -q 'vercel-deploy' && echo true || echo false)"
  

  build-and-deploy:
    needs: check_commit
    if: ${{ needs.check_commit.outputs.trigger == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install Vercel CLI
        run: bun i -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
